version: '3'
services:
  api:
    build: .
    container_name: api_server
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    command: ["node", "api/index.js"]
    depends_on:
      - client

  client:
    build:
      context: ./client
    container_name: client_server
    ports:
      - "8080:80"
    volumes:
      - ./client:/usr/share/nginx/html
    depends_on:
      - api
