version: '3'
services:
  api:
    build: ./api
    container_name: api-server
    ports:
      - "3000:3000"
    volumes:
      - ./app:/usr/src/app
    depends_on:
      - mongo

  client:
    build:
      context: ./client
    container_name: web-client
    ports:
      - "8080:80"
    volumes:
      - ./client:/usr/share/nginx/html
    depends_on:
      - api

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-data:/data/db
