name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Jalankan pipeline saat ada push ke branch 'main'
  pull_request:
    branches:
      - main  # Jalankan pipeline pada PR yang ditargetkan ke 'main'

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:20.10.16
        options: --privileged

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3


    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Build and push API Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/plant-watering-api:latest -f api/Dockerfile .
        docker push ${{ secrets.DOCKER_HUB_USERNAME }}/plant-watering-api:latest

    - name: Build and push Client Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/plant-watering-client:latest -f client/Dockerfile .
        docker push ${{ secrets.DOCKER_HUB_USERNAME }}/plant-watering-client:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Setup SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

    - name: Deploy API and Client Containers
      run: |
        ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
        docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/plant-watering-api:latest
        docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/plant-watering-client:latest

        # Jalankan API container di port 3000
        docker run -d -p 3000:3000 --name api_server ${{ secrets.DOCKER_HUB_USERNAME }}/plant-watering-api:latest
        
        # Jalankan Client container di port 8080
        docker run -d -p 8080:80 --name client_server ${{ secrets.DOCKER_HUB_USERNAME }}/plant-watering-client:latest
